[options]
girs_directories = ["../gir-files"]
library = "Gedit"
version = "3.0"
min_cfg_version = "41"
target_path = "."
work_mode = "normal"
generate_builder = true
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true

generate = [
	"Gedit.App",
	"Gedit.AppActivatable",

	"Gedit.DebugSection",
	"Gedit.Document",
	"Gedit.EncodingsComboBox",
	"Gedit.MenuExtension",

	"Gedit.Message",
	"Gedit.MessageBus",
	"Gedit.MessageBusForeach",
	"Gedit.MessageCallback",

	"Gedit.ProgressInfoBar",
	"Gedit.Statusbar",

	"Gedit.Tab",
	"Gedit.TabState",

	"Gedit.View",
	"Gedit.ViewActivatable",

	"Gedit.Window",
	"Gedit.WindowActivatable",
	"Gedit.WindowState",
]

manual = [
	"Gdk.DragContext",
	"Gdk.Event",
	"Gdk.Rectangle",
	"Gdk.Screen",

	"Gio.AsyncReadyCallback",
	"Gio.AsyncResult",
	"Gio.Cancellable",
	"Gio.File",
	"Gio.InputStream",
	"Gio.Menu",
	"Gio.MenuItem",

	"GLib.DestroyNotify",

	"Gtk.Application",
	"Gtk.ApplicationWindow",
	"Gtk.Bin",
	"Gtk.Container",
	"Gtk.Infobar",
	"Gtk.SelectionData",
	"Gtk.Statusbar",
	"Gtk.TextBuffer",
	"Gtk.TextView",
	"Gtk.TreeView",
	"Gtk.Widget",
	"Gtk.Window",
	"Gtk.WindowGroup",

	"GtkSource.Buffer",
	"GtkSource.CompressionType",
	"GtkSource.Encoding",
	"GtkSource.File",
	"GtkSource.Language",
	"GtkSource.NewlineType",
	"GtkSource.SearchContext",
	"GtkSource.View",
]
