[options]
library = "Gedit"
version = "3.0"
target_path = "."
min_cfg_version = "41"
work_mode = "sys"
girs_directories = ["../../gir-files/"]

external_libraries = [
	"Gdk",
	"Gio",
	"GLib",
	"GObject",
	"Gtk",
	"GtkSource",
]
